# Generated by Django 3.2.7 on 2021-10-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qr',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='qr',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
