# Generated by Django 3.2.7 on 2021-10-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_api', '0002_auto_20211030_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
