# Generated by Django 3.2.7 on 2021-10-30 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_api', '0003_alter_qr_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qr',
            name='url',
        ),
    ]
